[package]
name = "ingot"
version = "0.1.0"
authors = ["rookie1024 <rookie1286@gmail.com>"]

[dependencies]
gdk-pixbuf = "0.5.0"
gio = "0.5.0"
glib = "0.6.0"
gtk = { version = "0.5.0", features = ["v3_14"] }
image = "0.20.0"
nalgebra = "0.16.5"
num_cpus = "1.8.0"
rand = "0.5.5"
